project:
  type: website
  resources:
    - lectures/14/14-decision-errors.pdf

website:
  page-navigation: true
  title: "STA 101 - F23"
  description: "Homepage for STA 101 - Data Analysis and Statistical Inference at Duke University, Fall 2023."
  site-url: "https://sta101-f23.github.io"

  repo-url: https://github.com/sta101-f23/sta101-f23.github.io
  repo-actions: [edit, issue]

  open-graph: true

  sidebar:
    background: "#798b93"
    logo: "images/logo.png"
    pinned: true
    align: center

    tools:
      - icon: cloud
        href: https://posit.cloud/spaces/405361
        text: "Posit Cloud"
      - icon: slack
        href: https://sta101-f23.slack.com
        text: "Slack"
      - icon: file-play
        href: https://duke.hosted.panopto.com/Panopto/Pages/Sessions/List.aspx?folderID=a792a9f8-8b5d-432e-99e1-b06d01424ec4
        text: "Panopto"
      - icon: person-fill
        text: "Canvas"
        menu:
          - text: Announcements
            url: https://canvas.duke.edu/courses/4625/announcements
          - text: Grades
            url: https://canvas.duke.edu/courses/4625/gradebook
          - text: Tutorial submission
            url: https://canvas.duke.edu/courses/4625/quizzes
      - icon: github
        href: https://github.com/sta101-f23/sta101-f23.github.io

    style: docked
    search: true
    collapse-level: 1

    contents:
      - section: "Course information"
        contents:
          - href: course-overview.qmd
            text: Overview
          - href: course-syllabus.qmd
            text: Syllabus
          - href: course-support.qmd
            text: Support
          - href: course-team.qmd
            text: Teaching team
          - href: index.qmd
            text: Schedule
          - href: course-links.qmd
            text: Useful links
          - href: course-faq.qmd
            text: FAQ
      - section: "Labs"
        contents:
          - href: labs/lab-1.qmd
            text: Lab 1
          - href: labs/lab-2.qmd
            text: Lab 2
          - href: labs/lab-3.qmd
            text: Lab 3  
          - href: labs/lab-4.qmd
            text: Lab 4
          - href: labs/lab-5.qmd
            text: Lab 5
          - href: labs/lab-6.qmd
            text: Lab 6
          - href: labs/lab-7.qmd
            text: Lab 7
          - href: labs/lab-8.qmd
            text: Lab 8
      - section: "Projects"
        contents:
          - href: project/project-1.qmd
            text: "Project 1"
          - href: project/project-2.qmd
      - section: "Computing"
        contents:
          - href: computing/computing-access.qmd
            text: Access
          - href: computing/computing-troubleshooting.qmd
            text: Troubleshooting
          - href: computing/computing-cheatsheets.qmd
            text: Cheatsheets
      - href: extra-credit.qmd
        text: Extra credit

  page-footer:
    right: "This page is built with ü§ç and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2023, Mine √áetinkaya-Rundel"
    background: "#5d6d74"


format:
  html:
    theme:
      light: [cosmo, style/sta101.scss]
      dark: [cosmo, style/sta101.scss, style/dark.scss]
    linkcolor: "#798b93"
    toc: true
    code-copy: true
    code-overflow: wrap
    mainfont: "Atkinson Hyperlegible"

execute:
  freeze: auto

editor: visual
